package wannshan.springb.model;

import java.util.Date;

public class TSysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Long id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.menu_name
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.link
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.praent_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Long praentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.order
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.enabled
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.create_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.update_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.id
     *
     * @return the value of t_sys_menu.id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.id
     *
     * @param id the value for t_sys_menu.id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.menu_name
     *
     * @return the value of t_sys_menu.menu_name
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.menu_name
     *
     * @param menuName the value for t_sys_menu.menu_name
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.link
     *
     * @return the value of t_sys_menu.link
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.link
     *
     * @param link the value for t_sys_menu.link
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.praent_id
     *
     * @return the value of t_sys_menu.praent_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Long getPraentId() {
        return praentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.praent_id
     *
     * @param praentId the value for t_sys_menu.praent_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setPraentId(Long praentId) {
        this.praentId = praentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.order
     *
     * @return the value of t_sys_menu.order
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.order
     *
     * @param order the value for t_sys_menu.order
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.enabled
     *
     * @return the value of t_sys_menu.enabled
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.enabled
     *
     * @param enabled the value for t_sys_menu.enabled
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.create_time
     *
     * @return the value of t_sys_menu.create_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.create_time
     *
     * @param createTime the value for t_sys_menu.create_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.update_time
     *
     * @return the value of t_sys_menu.update_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.update_time
     *
     * @param updateTime the value for t_sys_menu.update_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}