package wannshan.springb.model;

import java.util.Date;

public class TSysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.user_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.role_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.create_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.id
     *
     * @return the value of t_sys_user_role.id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.id
     *
     * @param id the value for t_sys_user_role.id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.user_id
     *
     * @return the value of t_sys_user_role.user_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.user_id
     *
     * @param userId the value for t_sys_user_role.user_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.role_id
     *
     * @return the value of t_sys_user_role.role_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.role_id
     *
     * @param roleId the value for t_sys_user_role.role_id
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.create_time
     *
     * @return the value of t_sys_user_role.create_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.create_time
     *
     * @param createTime the value for t_sys_user_role.create_time
     *
     * @mbggenerated Tue Apr 17 10:14:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}